run-name: Terraform Production Release
name: Terraform Workflow Driver
on:
  workflow_dispatch:
  pull_request:
    types: [labeled]
  pull_request_review:
    types: [submitted]
    
# Prevent multiple parallel jobs as the terraform lock on the plan will fail      
concurrency:
  group: terraform
  cancel-in-progress: false

permissions:
  pull-requests: write # write permission in order to add comments for terraform output
  id-token: write # write permission is required for az login
  contents: write
      
jobs:

  prod-scenario-plan:
    if: github.event.review.state == 'APPROVED' || contains(github.event.pull_request.labels.*.name, 'production')
    uses: ./.github/workflows/terraform-plan.yaml
    with:
      working-dir: "terraform/proj1"
      terraform-version: "1.7.3"
      environment: production 
      saveplan: true
      planName: production.out

  prod-scenario-apply:
    if: github.event.review.state == 'APPROVED' || contains(github.event.pull_request.labels.*.name, 'production')
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      working-dir: "terraform/proj1"
      terraform-version: "1.7.3"
      environment: production
      planName: production.out

  auto-merge:
    uses: ./.github/workflows/github-automerge.yaml
    needs: [prod-scenario-apply]
    with:
      branch: ${{ github.head_ref }}
