run-name: Terraform Production Release
name: Terraform Production Release
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    
# Prevent multiple parallel jobs as the terraform lock on the plan will fail      
concurrency:
  group: terraform
  cancel-in-progress: false

permissions:
  pull-requests: write # write permission in order to add comments for terraform output
  id-token: write # write permission is required for az login
  contents: write
      
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Show Release Context
        run: |
          echo <<EOF
            ${{ toJSON (github) }}
          EOF

  prod-scenario-plan:
    if: github.event.pull_request.merged == true || contains(github.event.pull_request.labels.*.name, 'production')
    uses: ./.github/workflows/terraform-plan.yaml
    with:
      working-dir: "terraform/proj1"
      terraform-version: "1.9.5"
      environment: production 
      saveplan: true

  prod-scenario-apply:
    needs: [prod-scenario-plan]
    if: needs.prod-scenario-plan.outputs.plan-exitcode == '2' && (github.event.pull_request.merged == true || contains(github.event.pull_request.labels.*.name, 'production'))
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      working-dir: "terraform/proj1"
      terraform-version: "1.9.5"
      environment: production
      planName: ${{ needs.prod-scenario-plan.outputs.plan-name }}

  auto-merge:
    uses: ./.github/workflows/github-automerge.yaml
    needs: [prod-scenario-apply]
    with:
      branch: ${{ github.head_ref }}
